#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

cat << EOF > .env

BUILD_DATE=${BUILD_DATE}
BUILD_VERSION=${BUILD_VERSION}
BUILD_TYPE=${BUILD_TYPE}

QUASSELWEB_VERSION=${QUASSELWEB_VERSION}
QUASSELCORE_HOST=quassel-core

QUASSELWEB_FORCE_DEFAULT=false
QUASSELWEB_WEBSERVER_MODE=http
QUASSELWEB_PREFIX_PATH=/irc

EOF

docker-compose \
  --file compose/head.yml \
  --file compose/quassel-core.yml \
  --file compose/quassel-web.yml \
  config > docker-compose.yml
