#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

echo "BUILD_DATE=${BUILD_DATE}" > .env
echo "BUILD_VERSION=${BUILD_VERSION}" >> .env
echo "BUILD_TYPE=${BUILD_TYPE}" >> .env
echo "QUASSELWEB_VERSION=${QUASSELWEB_VERSION}" >> .env
echo "QUASSEL_HOST=172.17.0.1" >> .env
echo "FORCE_DEFAULT=true" >> .env
echo "WEBSERVER_MODE=https" >> .env
echo "PREFIX_PATH=/irc" >> .env

docker-compose \
  --file docker-compose_example.yml \
  config > docker-compose.yml
